import Link from "next/link";
import { FAQTopicPage, type FAQEntry } from "@/components/faq/FAQTopicPage";
import { buildPageMetadata } from "@/lib/seo/metadata";

export const metadata = buildPageMetadata({ title: "Drone Footage Licensing FAQ | OpenÉire Studios", description: "Get clear answers about drone footage licensing, pricing factors, rights-managed use, and commercial aerial footage usage.", path: "/faq/drone-footage-licensing" });

const faqs: FAQEntry[] = [
  { question: "How much does drone footage licensing cost?", answerLead: "Drone footage licensing cost depends on the intended use.", bullets: ["Duration", "Territory", "Media channels", "Exclusivity", "Whether the use is commercial or editorial"], bridge: <>For the full licensing route and scope details, continue to the <Link href="/licensing" className="text-accent hover:text-white">licensing page</Link>.</>, schemaAnswer: "Drone footage licensing cost depends on duration, territory, media channels, exclusivity, and whether the use is commercial or editorial." },
  { question: "What affects the price of aerial footage?", answerLead: "The price is shaped by how widely and how long the footage will be used.", answerParagraphs: ["A short local use is different from a multi-market campaign or wider distribution plan."], bridge: <>Start with the <Link href="/footage" className="text-accent hover:text-white">footage page</Link> and then read the <Link href="/blog/how-much-does-drone-footage-cost-in-ireland" className="text-accent hover:text-white">pricing guide</Link>.</>, schemaAnswer: "The price of aerial footage is shaped by how widely and how long the footage will be used." },
  { question: "Can I use drone footage for advertising?", answerLead: "Yes, advertising use normally requires a commercial licence.", answerParagraphs: ["If the footage is helping market a service, product, property, or destination, that is usually treated as commercial usage."], schemaAnswer: "Advertising use normally requires a commercial licence because it supports promotion of a service, product, property, or destination." },
  { question: "Do I need a licence for drone footage?", answerLead: "If the footage is being used beyond private personal use, a licence is usually required.", answerParagraphs: ["That includes most campaign, brand, client, editorial, and promotional contexts where the footage is published or distributed."], schemaAnswer: "A licence is usually required when footage is used beyond private personal viewing." },
  { question: "What does rights-managed mean?", answerLead: "Rights-managed means the licence is tied to a defined use rather than being unlimited.", answerParagraphs: ["The agreed scope usually reflects the project, where it appears, and how long it runs."], schemaAnswer: "Rights-managed means a licence is tied to a defined project, placement, territory, and duration." },
  { question: "Can drone footage be licensed for editorial use?", answerLead: "Yes, editorial use may be available for suitable publishing and documentary contexts.", answerParagraphs: ["Editorial use supports reporting, documentary, educational, or feature work rather than direct promotion."], schemaAnswer: "Editorial licensing may be available for suitable publishing, documentary, educational, and feature contexts." },
  { question: "What changes the scope of a footage licence?", answerLead: "The scope changes when the planned use changes.", bullets: ["A new campaign", "A wider territory", "Additional media channels", "A longer usage period", "A need for exclusivity"], schemaAnswer: "A new campaign, territory, media channel, usage period, or exclusivity requirement can change the scope of a footage licence." },
];

export default function DroneFootageLicensingFAQPage() { return <FAQTopicPage canonicalPath="/faq/drone-footage-licensing" breadcrumbLabel="Drone Footage Licensing FAQ" eyebrow="Drone footage licensing answers" heading="Drone Footage Licensing FAQ" intro="Answers for buyers trying to understand licensing, pricing factors, and rights-managed aerial footage before they request approval." supportingIntro="This page supports licensing decisions while pointing you back to available footage when you are choosing the right asset." faqs={faqs} ctaTitle="Need the full licensing route?" ctaText="Use the licensing page for the deeper decision layer, or return to the footage collection if you are still choosing the right asset." ctas={[{ label: "Go to Licensing", href: "/licensing" }, { label: "Browse Footage", href: "/footage", variant: "secondary" }, { label: "Read Pricing Guide", href: "/blog/how-much-does-drone-footage-cost-in-ireland", variant: "tertiary" }]} />; }
