import Link from "next/link";
import { FAQTopicPage, type FAQEntry } from "@/components/faq/FAQTopicPage";
import {
  formatFreeShippingThreshold,
  FREE_SHIPPING_COUNTRY_LABEL,
} from "@/lib/freeShipping";
import { buildPageMetadata } from "@/lib/seo/metadata";

export const metadata = buildPageMetadata({ title: "Art Prints FAQ | OpenÉire Studios", description: "Find answers about fine art prints, shipping, gifting, formats, and buying aerial photography prints from OpenÉire Studios.", path: "/faq/art-prints" });

const freeShippingThreshold = formatFreeShippingThreshold();
const freeShippingAnswer = `Eligible physical orders over ${freeShippingThreshold} qualify for free delivery in ${FREE_SHIPPING_COUNTRY_LABEL}.`;

const faqs: FAQEntry[] = [
  { question: "Do you ship fine art prints to the United States?", answerLead: "Yes, we ship prints to the United States.", answerParagraphs: ["You can order directly through the site, and shipping is calculated at checkout based on your location and the print."], bridge: <>See the <Link href="/us/fine-art-prints" className="text-accent hover:text-white">United States fine art prints page</Link>.</>, schemaAnswer: "Prints are available to buyers in the United States, with shipping calculated at checkout." },
  { question: "What kind of prints do you sell?", answerLead: "We sell premium wall art prints created from original aerial and ground photography.", answerParagraphs: ["Each piece is designed as a finished artwork with a focus on composition, atmosphere, and perspective."], schemaAnswer: "OpenÉire Studios sells premium wall art prints created from original aerial and ground photography." },
  { question: "Are these original aerial photography prints?", answerLead: "Yes, every print comes from original photography.", answerParagraphs: ["The collection is captured and curated by OpenÉire Studios rather than sourced from stock libraries."], schemaAnswer: "All prints are based on original photography created and curated by OpenÉire Studios." },
  { question: "Are prints suitable for gifting?", answerLead: "Yes, they work very well as a gift.", answerParagraphs: ["Their distinctive, design-led character makes them a considered alternative to standard wall decor."], schemaAnswer: "The prints are suitable for gifting and provide a distinctive alternative to standard wall decor." },
  { question: "What sizes or formats are available?", answerLead: "Sizes and formats vary by print.", answerParagraphs: ["Each product page shows the exact dimensions and format options available for that piece."], schemaAnswer: "Sizes and formats vary by print and are listed on each product page." },
  { question: "Are prints framed?", answerLead: "Framing depends on the specific print you choose.", answerParagraphs: ["Check the product listing or contact the studio if you need confirmation before ordering."], schemaAnswer: "Framing availability depends on the individual print and is shown on its product page." },
  { question: "Are these limited edition?", answerLead: "Some prints may be limited, but not all are.", answerParagraphs: ["Limited-edition status is clearly stated on the product page where applicable."], schemaAnswer: "Some prints may be limited edition, as specified on the individual product page." },
  { question: "How is shipping handled for print orders?", answerLead: "Shipping is handled during checkout.", answerParagraphs: ["Delivery methods and costs are calculated securely for the selected print and destination."], schemaAnswer: "Shipping methods and costs are calculated during checkout." },
  { question: "When is shipping calculated for print orders?", answerLead: "Shipping is calculated at checkout.", answerParagraphs: ["The final cost depends on the print, size, delivery location, and available fulfilment method."], schemaAnswer: "Shipping is calculated at checkout based on print, size, location, and fulfilment method." },
  { question: `Do you offer free shipping in ${FREE_SHIPPING_COUNTRY_LABEL}?`, answerLead: freeShippingAnswer, answerParagraphs: ["The promotion is applied automatically when the order qualifies."], schemaAnswer: freeShippingAnswer },
  { question: "How long does print fulfilment usually take?", answerLead: "Fulfilment time depends on the print and delivery location.", answerParagraphs: ["Most orders are produced and shipped within a few working days, with delivery time depending on the selected method."], schemaAnswer: "Fulfilment time depends on the print, destination, and selected delivery method." },
  { question: "What should I do if I need help before ordering?", answerLead: "Contact the studio before placing an order.", answerParagraphs: ["We can help with choosing a piece, sizing, framing, or delivery questions."], bridge: <>Use the <Link href="/contact" className="text-accent hover:text-white">contact page</Link> to get in touch.</>, schemaAnswer: "Contact the studio for help choosing a print or clarifying details before ordering." },
];

export default function ArtPrintsFAQPage() { return <FAQTopicPage canonicalPath="/faq/art-prints" breadcrumbLabel="Art Prints FAQ" eyebrow="Art print buying answers" heading="Art Prints FAQ" intro="Answers for buyers who want a clearer picture of what the print product is, how ordering works, and what to expect before they buy." supportingIntro="This page supports the print-buying journey without replacing the collection pages themselves." faqs={faqs} ctaTitle="Ready to browse prints?" ctaText="Start with the art prints overview or go straight into the physical print gallery to inspect available pieces." ctas={[{ label: "Go to Art Prints", href: "/art-prints" }, { label: "Open Print Gallery", href: "/gallery/physical", variant: "secondary" }, { label: "Contact the Studio", href: "/contact", variant: "tertiary" }]} />; }
