import Link from "next/link";
import { FAQTopicPage, type FAQEntry } from "@/components/faq/FAQTopicPage";
import { buildPageMetadata } from "@/lib/seo/metadata";

export const metadata = buildPageMetadata({ title: "Drone Footage Usage FAQ | OpenÉire Studios", description: "Learn what you can and cannot do with licensed drone footage, including commercial use, social media, editing, and ownership questions.", path: "/faq/drone-footage-usage" });

const faqs: FAQEntry[] = [
  { question: "Can I use drone footage without permission?", answerLead: "Not for most public, commercial, or editorial uses.", answerParagraphs: ["If the footage is copyrighted and you are using it beyond private personal viewing, you should assume permission is required."], bridge: <>Review the <Link href="/licensing" className="text-accent hover:text-white">licensing page</Link> before publishing.</>, schemaAnswer: "Permission is required for most public, commercial, or editorial uses of copyrighted drone footage." },
  { question: "What counts as commercial use?", answerLead: "Commercial use usually means the footage supports a business, organisation, campaign, client, or promotion.", bullets: ["Advertising", "Brand campaigns", "Property marketing", "Paid social content", "Client work"], schemaAnswer: "Commercial use includes advertising, brand campaigns, property marketing, paid social content, and client work." },
  { question: "Can I use drone footage on social media?", answerLead: "Yes, but the answer depends on what kind of social media use it is.", answerParagraphs: ["Private personal posting is different from branded, client, promotional, or paid social use."], schemaAnswer: "Social media use may be permitted, but branded, client, promotional, or paid use normally requires licensing." },
  { question: "Do I own the footage after buying it?", answerLead: "No. Buying or licensing footage does not usually transfer copyright ownership.", answerParagraphs: ["You receive permission for a defined use rather than acquiring the underlying rights."], schemaAnswer: "Licensing footage grants permission for a defined use and does not transfer copyright ownership." },
  { question: "What is the difference between personal and commercial use?", answerLead: "Personal use is private. Commercial use supports business, promotion, or client-facing activity.", answerParagraphs: ["The same footage can sit in different categories depending on where and why it is published."], schemaAnswer: "Personal use is private, while commercial use supports business, promotional, or client-facing activity." },
  { question: "Can I reuse licensed footage in a new campaign?", answerLead: "Not automatically.", answerParagraphs: ["A new campaign may fall outside the original scope if the audience, territory, timing, or media plan has changed."], schemaAnswer: "A new campaign may require a new licence if its audience, territory, timing, or media plan differs from the original scope." },
  { question: "Can I edit or crop licensed drone footage?", answerLead: "Possibly, but that depends on the permitted use.", answerParagraphs: ["Usage permissions should match the way the footage is adapted and published."], bridge: <>Start with the <Link href="/footage" className="text-accent hover:text-white">footage page</Link> and then confirm the licensing route.</>, schemaAnswer: "Editing or cropping may be permitted when it remains within the agreed licence scope." },
];

export default function DroneFootageUsageFAQPage() { return <FAQTopicPage canonicalPath="/faq/drone-footage-usage" breadcrumbLabel="Drone Footage Usage FAQ" eyebrow="Drone footage usage answers" heading="Drone Footage Usage FAQ" intro="Answers for buyers working out what counts as permitted use, where permission is needed, and how commercial and personal use differ." supportingIntro="Use this page when the main question is what you can do with footage once you have it." faqs={faqs} ctaTitle="Need the next step?" ctaText="If you are ready to confirm permissions, go to licensing. If you are still choosing source material, return to the footage page first." ctas={[{ label: "Go to Licensing", href: "/licensing" }, { label: "Browse Footage", href: "/footage", variant: "secondary" }, { label: "Read Licensing Guide", href: "/blog/how-to-license-drone-footage-in-ireland-complete-guide", variant: "tertiary" }]} />; }
